// mock data for testing
// DO NOT FORGET TO REMOVE THIS BEFORE PRODUCTION DEPLOYMENT

// ID, name, model,serial number, description, quantity in stocks, price, 
// warranty status, and distributor information.

import { Op } from "sequelize";
import db from "../entities";

const mockProducts = [
  {
    name: "Velvet Matte Lipstick",
    brand: "LumaBelle",
    category: "makeup",
    model: "Velvet Matte Pro",
    serial_number: "LB-VML-001",
    description: "A smooth matte lipstick with rich color payoff and comfortable all-day wear.",
    quantity_in_stock: 24,
    price: 28,
    original_price: 35,
    rating: 4.6,
    review_count: 312,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa",
    badge: "BEST",
    warranty_status: true,
    distributor_info: "LumaBelle International",
  },
  {
    name: "Radiance Boost Serum",
    brand: "GlowLab",
    category: "skincare",
    model: "Radiance Pro",
    serial_number: "GL-RBS-002",
    description: "A brightening serum with vitamin C, niacinamide, and hyaluronic acid.",
    quantity_in_stock: 15,
    price: 54,
    original_price: 68,
    rating: 4.7,
    review_count: 487,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be",
    badge: "NEW",
    warranty_status: true,
    distributor_info: "GlowLab Cosmetics",
  },
  {
    name: "Pro Glow Eyeshadow Palette",
    brand: "LumaBelle",
    category: "makeup",
    model: "Pro Glow 12",
    serial_number: "LB-PGP-003",
    description: "A 12-shade eyeshadow palette with matte, shimmer, and metallic finishes.",
    quantity_in_stock: 18,
    price: 62,
    original_price: null,
    rating: 4.8,
    review_count: 541,
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796",
    badge: "BEST",
    warranty_status: true,
    distributor_info: "LumaBelle International",
  },
  {
    name: "Men's Beard and Face Kit",
    brand: "ForHim",
    category: "men-care",
    model: "Beard Face Kit",
    serial_number: "FH-BFK-004",
    description: "A grooming kit with beard oil, cleanser, and lightweight moisturizer.",
    quantity_in_stock: 32,
    price: 48,
    original_price: 60,
    rating: 4.3,
    review_count: 113,
    image: "https://images.unsplash.com/photo-1621607512214-68297480165e",
    badge: "NEW",
    warranty_status: true,
    distributor_info: "ForHim Grooming Co.",
  },
  {
    name: "Men's Active Cleanser",
    brand: "ForHim",
    category: "men-care",
    model: "Active Cleanser",
    serial_number: "FH-MAC-005",
    description: "A daily facial cleanser made for active skin and post-workout refresh.",
    quantity_in_stock: 45,
    price: 22,
    original_price: 28,
    rating: 4.2,
    review_count: 96,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03",
    badge: null,
    warranty_status: true,
    distributor_info: "ForHim Grooming Co.",
  },
  {
    name: "Luxury Perfume Collection",
    brand: "Aurore",
    category: "makeup",
    model: "Signature Trio",
    serial_number: "AU-LPC-006",
    description: "A gift-ready set of three signature fragrances for day, evening, and special occasions.",
    quantity_in_stock: 9,
    price: 89,
    original_price: null,
    rating: 4.6,
    review_count: 234,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601",
    badge: "LIMITED",
    warranty_status: true,
    distributor_info: "Aurore Paris",
  },
  {
    name: "Complete Skincare Bundle",
    brand: "GlowLab",
    category: "skincare",
    model: "Complete Set",
    serial_number: "GL-CSB-007",
    description: "A full skincare routine with cleanser, toner, serum, moisturizer, and SPF.",
    quantity_in_stock: 0,
    price: 118,
    original_price: 160,
    rating: 4.4,
    review_count: 89,
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883",
    badge: "SALE",
    warranty_status: true,
    distributor_info: "GlowLab Cosmetics",
  },
  {
    name: "Silk Repair Hair Oil",
    brand: "HairLux",
    category: "haircare",
    model: "Silk Repair Oil",
    serial_number: "HL-SHO-008",
    description: "A lightweight hair oil that adds shine and helps smooth dry ends.",
    quantity_in_stock: 27,
    price: 38,
    original_price: null,
    rating: 4.5,
    review_count: 205,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9",
    badge: "NEW",
    warranty_status: true,
    distributor_info: "HairLux Laboratories",
  },
  {
    name: "Deep Hydration Face Cream",
    brand: "GlowLab",
    category: "skincare",
    model: "Hydration Cream",
    serial_number: "GL-DHC-009",
    description: "A rich face cream that supports soft, hydrated skin through the day.",
    quantity_in_stock: 36,
    price: 42,
    original_price: null,
    rating: 4.3,
    review_count: 178,
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b",
    badge: null,
    warranty_status: true,
    distributor_info: "GlowLab Cosmetics",
  },
  {
    name: "Volumizing Shampoo",
    brand: "HairLux",
    category: "haircare",
    model: "Volume Shampoo",
    serial_number: "HL-VS-010",
    description: "A gentle shampoo that cleanses roots and gives fine hair a fuller look.",
    quantity_in_stock: 22,
    price: 26,
    original_price: 32,
    rating: 4.1,
    review_count: 143,
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d",
    badge: null,
    warranty_status: true,
    distributor_info: "HairLux Laboratories",
  },
];

export async function seedMockProducts() {
  const serials = mockProducts.map((item) => item.serial_number);
  const existing = await db.products.findAll({
    where: { serial_number: { [Op.in]: serials } },
  });

  const existingSerials = new Set(existing.map((product: any) => product.serial_number));
  const toCreate = mockProducts.filter(
    (product: any) => !existingSerials.has(product.serial_number)
  );

  if (toCreate.length === 0) {
    console.log("Mock products already exist, skipping seeding.");
    return;
  }

  await db.products.bulkCreate(toCreate);
  console.log(`Seeded ${toCreate.length} mock products.`);
}
